### 1. Numpy 시작

In [6]:
arr = [1,"two", 3.0]        # 파이썬 list는 다른 type을 저장해도 무방

print(arr)

[1, 'two', 3.0]


In [7]:
import numpy as np 

In [8]:
L  = range(1000)

%timeit [i**2 for i in L]       # List comprehension


189 µs ± 909 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [10]:
N = np.arange(1000)

In [11]:
%timeit N **2

1.36 µs ± 3.89 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [12]:
arr = np.array([1,2,3])

arr

array([1, 2, 3])

In [14]:
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
 arr.shape

(3,)

In [16]:
arr_2d.shape

(3, 3)

### Vector와 Scalar 사이의 연산

In [18]:
x = np.array([1,2,3])
c = 5

print("더하기 : {}".format(x+c))

더하기 : [6 7 8]


In [19]:
print("곱하기 : {}".format(x*c))
print("나누기 : {}".format(x/c))
print("거듭제곱 : {}".format(x**c))

곱하기 : [ 5 10 15]
나누기 : [0.2 0.4 0.6]
거듭제곱 : [  1  32 243]


### Vector와 Vector 사이의 연산


In [21]:
y= np.array([1,3,5])
z =np.array([2,9,20])

print("더하기 : {}".format(y+z))
print("곱하기 : {}".format(y*z))
print("나누기 : {}".format(y/z))
print("거듭제곱 : {}".format(y**z))

더하기 : [ 3 12 25]
곱하기 : [  2  27 100]
나누기 : [0.5        0.33333333 0.25      ]
거듭제곱 : [         1      19683 1977800241]


### Array Indexing

In [22]:
W = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

W[0,0]

1

In [23]:
W[2,3]

12

### Array Slicing

In [25]:
W = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

W[0:2, 1:3]

array([[2, 3],
       [6, 7]])

In [35]:
W[-3, 1:3]

array([2, 3])

### Array Broadcastring

1. M by N, M by 1

In [55]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
x = np.array([0,1,0])

# x를 전치해줄 방법?
x=x[:,None]
#x=np.transpose([x])
print(a+x)

[[1 2 3]
 [5 6 7]
 [7 8 9]]


2. M by N, 1 by N


In [57]:
y = np.array([0,1,-1])

print(a*y)

[[ 0  2 -3]
 [ 0  5 -6]
 [ 0  8 -9]]


3. M by 1, 1 by N


In [58]:
t = np.array([1,2,3])
t=np.transpose([t])

u= np.array([2,0,-2])

print(t+u)


[[ 3  1 -1]
 [ 4  2  0]
 [ 5  3  1]]


### 영벡터 생성

In [60]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### 일벡터 생성

In [61]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 대각행렬 생성

In [62]:
np.diag((2,4))

array([[2, 0],
       [0, 4]])

### 항등행렬

In [64]:
np.eye(2,dtype=int)

array([[1, 0],
       [0, 1]])

### 행렬곱

In [66]:
mat_1 = np.array([[1,4],[2,3]])
mat_2 = np.array([[7,9],[0,6]])

mat_1.dot(mat_2)

array([[ 7, 33],
       [14, 36]])

In [68]:
mat_1 @ mat_2

array([[ 7, 33],
       [14, 36]])

### 트레이스

In [69]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

arr.trace()

15

In [70]:
np.eye(2,dtype=int).trace()



2

### 행렬식(determinant) 계산

In [71]:
arr_3 = np.array([[1,4,7],[2,5,8],[3,6,9]])

np.linalg.det(arr_3)

0.0

### 역행렬

In [73]:
 mat = np.array([[1,4],[2,3]])

 mat_inv = np.linalg.inv(mat)

In [74]:
mat_inv

array([[-0.6,  0.8],
       [ 0.4, -0.2]])

### eigenvalue 와 eigenvector

In [76]:
mat =np.array([[2,0,-2],[1,1,-2],[0,0,1]])

np.linalg.eig(mat)

(array([1., 2., 1.]),
 array([[0.        , 0.70710678, 0.89442719],
        [1.        , 0.70710678, 0.        ],
        [0.        , 0.        , 0.4472136 ]]))

In [77]:
eig_val, eig_vec = np.linalg.eig(mat)

eig_val

array([1., 2., 1.])

In [78]:
eig_vec

array([[0.        , 0.70710678, 0.89442719],
       [1.        , 0.70710678, 0.        ],
       [0.        , 0.        , 0.4472136 ]])

In [79]:
mat @ eig_vec[:,0]

array([0., 1., 0.])

In [83]:
eig_val[0] * eig_vec[:,2]

array([0.89442719, 0.        , 0.4472136 ])

1. 어떤 벡터가 주어졌을 때 L2 norm을 구하는 함수 get_L2_norm()

In [91]:
def get_L2_norm(arr):
    return np.sqrt(sum(arr**2))

In [95]:
exer_arr1 = np.array([1,2,3,4,5])

%timeit get_L2_norm(exer_arr1)

3.2 µs ± 11.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [96]:
%timeit np.linalg.norm(exer_arr1)   # 구글에서 찾은 numpy norm


3.8 µs ± 33.1 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


2. 어떤 행렬이 singular matrix인지 확인하는 함수 is_singular() 작성

In [98]:
#singular matrix란 역행렬이 존재하지 않는 행렬
#Determinant가 0이라면 singular matrix

def is_singular(arr):
    return True if np.linalg.det(arr)==0 else False

In [102]:
exer_arr2=np.array([[1,4,7],[2,5,8],[3,6,9]])

print(is_singular(exer_arr2))

True
0.0
