<a href="https://colab.research.google.com/github/LeeJuCheon/TIL_devcourse/blob/main/week9/week9-4-2_tensor_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
%matplotlib inline            
# plt.show 없이 출력 가능하게

# PyTorch
* Numpy를 대체하면서 GPU를 이용한 연산이 필요한 경우
* 최대한의 유연성과 속도를 제공하는 딥러닝 연구 플랫폼이 필요한 경우

In [2]:
from __future__ import print_function     # 파이썬 버전에 상관없이 print() 출력가능
import torch

torch.__version__

'1.10.0+cu111'

In [6]:
# 5x3 행렬 생성, 초기화 X
x=torch.empty(5,3)
print(x)

tensor([[3.2920e-19, 3.0705e-41, 3.3631e-44],
        [0.0000e+00,        nan, 6.4460e-44],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 0.0000e+00]])


In [3]:
x = torch.randn(5,3)  # 정규분포에서 샘플링
print(x)
x=torch.rand(5,3)     # 0~1사이의 수 샘플링
print(x)

tensor([[-0.5390, -0.9360, -1.0315],
        [ 1.4262,  0.4548, -0.8258],
        [-2.2317,  0.3648, -2.6564],
        [ 0.8303,  0.4834, -0.6468],
        [-1.0962,  0.8162,  1.3509]])
tensor([[0.4628, 0.3067, 0.7877],
        [0.6594, 0.2261, 0.4802],
        [0.2277, 0.9935, 0.7191],
        [0.4909, 0.7561, 0.0712],
        [0.2679, 0.6213, 0.8272]])


In [5]:
x = torch.zeros(5,3, dtype=torch.long)    # dtype이 long, 0으로 채워진 행렬
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [7]:
x = torch.ones(5,3,dtype=torch.long)      # dtype이 long, 1로 채워진 행렬
print(x)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])


In [8]:
x= torch.tensor([5.5,3])      # tensor 직접 생성
print(x)

tensor([5.5000, 3.0000])


In [10]:
x = x.new_ones(5,3,dtype = torch.double)    
print(x)

x= torch.randn_like(x, dtype=torch.float)     # type override
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.1174, -1.3793,  0.5630],
        [-0.9232,  0.6521,  1.9861],
        [-1.1819, -0.7354,  0.2193],
        [-0.9165, -0.6830, -1.1922],
        [-1.9040,  1.3106, -0.6539]])


In [11]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


In [12]:
y = torch.rand(5,3)
print(x)
print(y)
print(x+y)

tensor([[ 1.1174, -1.3793,  0.5630],
        [-0.9232,  0.6521,  1.9861],
        [-1.1819, -0.7354,  0.2193],
        [-0.9165, -0.6830, -1.1922],
        [-1.9040,  1.3106, -0.6539]])
tensor([[0.9174, 0.2586, 0.1546],
        [0.2547, 0.1699, 0.1632],
        [0.0857, 0.6475, 0.9984],
        [0.9413, 0.7723, 0.3911],
        [0.6656, 0.2960, 0.8131]])
tensor([[ 2.0348, -1.1206,  0.7176],
        [-0.6685,  0.8220,  2.1492],
        [-1.0962, -0.0879,  1.2177],
        [ 0.0248,  0.0893, -0.8011],
        [-1.2384,  1.6065,  0.1592]])


In [13]:
print(torch.add(x,y))

tensor([[ 2.0348, -1.1206,  0.7176],
        [-0.6685,  0.8220,  2.1492],
        [-1.0962, -0.0879,  1.2177],
        [ 0.0248,  0.0893, -0.8011],
        [-1.2384,  1.6065,  0.1592]])


In [14]:
result = torch.empty(5,3)
print(result)

torch.add(x,y,out=result)
print(result)

tensor([[-1.5472e+16,  3.0836e-41,  3.3631e-44],
        [ 0.0000e+00,         nan,  1.5028e+00],
        [ 1.1578e+27,  1.1362e+30,  7.1547e+22],
        [ 4.5828e+30,  1.2121e+04,  7.1846e+22],
        [ 9.2198e-39,  7.0374e+22,  6.7101e-01]])
tensor([[ 2.0348, -1.1206,  0.7176],
        [-0.6685,  0.8220,  2.1492],
        [-1.0962, -0.0879,  1.2177],
        [ 0.0248,  0.0893, -0.8011],
        [-1.2384,  1.6065,  0.1592]])


In [15]:
print(y)
y.add_(x)
print(y)        # 바꿔치기(in-place) 방식 , 새로 생성하지 않는 기법

tensor([[0.9174, 0.2586, 0.1546],
        [0.2547, 0.1699, 0.1632],
        [0.0857, 0.6475, 0.9984],
        [0.9413, 0.7723, 0.3911],
        [0.6656, 0.2960, 0.8131]])
tensor([[ 2.0348, -1.1206,  0.7176],
        [-0.6685,  0.8220,  2.1492],
        [-1.0962, -0.0879,  1.2177],
        [ 0.0248,  0.0893, -0.8011],
        [-1.2384,  1.6065,  0.1592]])


In [16]:
print(x)
print(x[:,1])

tensor([[ 1.1174, -1.3793,  0.5630],
        [-0.9232,  0.6521,  1.9861],
        [-1.1819, -0.7354,  0.2193],
        [-0.9165, -0.6830, -1.1922],
        [-1.9040,  1.3106, -0.6539]])
tensor([-1.3793,  0.6521, -0.7354, -0.6830,  1.3106])


In [17]:
x = torch.randn(4,4)
print(x)

y= x.view(16)     #16개의 차원을 가진 벡터 생성, numpy의 reshape와 비슷
z= y.view(-1,2)   
print(y)
print(z)
print(y.size(),z.size())

tensor([[ 1.5622,  1.4879, -0.8676, -1.7500],
        [-0.9716, -0.4979, -0.6406, -2.1004],
        [ 0.1970,  1.1878,  0.7916, -1.3586],
        [-0.1473,  1.3853,  1.5678, -1.3228]])
tensor([ 1.5622,  1.4879, -0.8676, -1.7500, -0.9716, -0.4979, -0.6406, -2.1004,
         0.1970,  1.1878,  0.7916, -1.3586, -0.1473,  1.3853,  1.5678, -1.3228])
tensor([[ 1.5622,  1.4879],
        [-0.8676, -1.7500],
        [-0.9716, -0.4979],
        [-0.6406, -2.1004],
        [ 0.1970,  1.1878],
        [ 0.7916, -1.3586],
        [-0.1473,  1.3853],
        [ 1.5678, -1.3228]])
torch.Size([16]) torch.Size([8, 2])


In [19]:
x = torch.randn(1)
print(x)
print(type(x), type(x.item()))
print(x.item())

tensor([0.0058])
<class 'torch.Tensor'> <class 'float'>
0.005804881919175386


https://pytorch.org/docs/torch

# NumPy 변환(Bridge)

TorchTensor를 NumPy 배열로 변환하거나 역의 경우

<b> Torch Tensor와 NumPy 배열은 저장공간을 공유한다.

In [20]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [21]:
b= a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [22]:
a.add_(1)     # in-place
print(a)
print(b)      # 저장공간을 공유했기 때문에 1이 더해짐

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [23]:
temp = a.clone()          # 저장공간을 분리하고 싶을 때
temp_numpy = temp.numpy()

a.add_(1)
print(a)
print(temp_numpy)

tensor([3., 3., 3., 3., 3.])
[2. 2. 2. 2. 2.]


In [24]:
import numpy as np
a  = np.ones(5)
print(a)
b= torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


array를 tensor로 : b= torch.from_numpy(a)

tensor를 array로 : b = a.numpy()

In [26]:
import torch
# CUDA 사용 가능한 환경에서만 실행 가능

x = torch.rand(4,4)
if torch.cuda.is_available():
  device = "cuda:0"     # torch.device("cuda:0")      # CUDA 장치 객체로
  y= torch.ones_like(x,device=device)
  print(y)

  x= x.to(device)
  z= x+y
  print(z)
  print(z.to("cpu",torch.double))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], device='cuda:0')
tensor([[1.5013, 1.0810, 1.2316, 1.9395],
        [1.7441, 1.3976, 1.0676, 1.7036],
        [1.8732, 1.1520, 1.5145, 1.0633],
        [1.5854, 1.4077, 1.1061, 1.1437]], device='cuda:0')
tensor([[1.5013, 1.0810, 1.2316, 1.9395],
        [1.7441, 1.3976, 1.0676, 1.7036],
        [1.8732, 1.1520, 1.5145, 1.0633],
        [1.5854, 1.4077, 1.1061, 1.1437]], dtype=torch.float64)


In [27]:
x = x.cuda()

# Tensorflow 실습

In [28]:
import tensorflow as tf
print(tf.__version__)

2.8.0


In [31]:
my_variable = tf.Variable(tf.zeros([1,2,3]))
my_variable

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

In [33]:
v = tf.Variable(0.0)
print(v)

w = v+1

print(w)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=0.0>
tf.Tensor(1.0, shape=(), dtype=float32)


In [34]:
a = tf.Variable(0.0)
a.assign_add(1)
a.read_value()  # 1.0

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [35]:
# Rank : 차원의 수

# Rank 0
mammal = tf.Variable("코끼리",tf.string)
ignition = tf.Variable(451, tf.int16)
floating = tf. Variable(3.14159265359,tf.float64)
its_complicated = tf.Variable(12.3 - 4.85j,tf.complex64)

print(mammal)
print(ignition)
print(floating)
print(its_complicated)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'\xec\xbd\x94\xeb\x81\xbc\xeb\xa6\xac'>
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=451>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.1415927>
<tf.Variable 'Variable:0' shape=() dtype=complex128, numpy=(12.3-4.85j)>


In [37]:
# 랭크 1(벡터)

mystr = tf.Variable(["안녕하세요"], tf.string)
cool_numbers = tf.Variable([3.14159,2.71828],tf.float32)
first_primes = tf.Variable([2,3,5,7,11],tf.int32)
its_very_complicated = tf.Variable([12.3-4.85j,7.5-6.23j],tf.complex64)

print(mystr)
print(cool_numbers)
print(first_primes)
print(its_very_complicated)
tf.rank(mystr)

<tf.Variable 'Variable:0' shape=(1,) dtype=string, numpy=
array([b'\xec\x95\x88\xeb\x85\x95\xed\x95\x98\xec\x84\xb8\xec\x9a\x94'],
      dtype=object)>
<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([3.14159, 2.71828], dtype=float32)>
<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([ 2,  3,  5,  7, 11], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2,) dtype=complex128, numpy=array([12.3-4.85j,  7.5-6.23j])>


<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [38]:
# 고차원 랭크

mymat = tf.Variable([[7],[11]],tf.int16)
myxor = tf.Variable([[False,True],[True,False]],tf.bool)
linear_squares = tf.Variable([[4],[9],[16],[25]],tf.int32)
squarish_squares = tf.Variable([[4,9],[16,25]],tf.int32)

rank_of_squares = tf.rank(squarish_squares)
mymatC = tf.Variable([[7],[11]],tf.int32)

print(mymat)
print(rank_of_squares)


<tf.Variable 'Variable:0' shape=(2, 1) dtype=int32, numpy=
array([[ 7],
       [11]], dtype=int32)>
tf.Tensor(2, shape=(), dtype=int32)


In [40]:
# 원소 참조하기(인덱스 참조)
my_vector = tf.Variable([1,2,3,4],tf.int32)
print(tf.rank(my_vector))
my_scalar = my_vector[2]
print(my_scalar)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)


In [41]:
my_scalar = squarish_squares[1,0]
print(my_scalar)

tf.Tensor(16, shape=(), dtype=int32)


In [42]:
# tf.Tensor 객체 형태 얻기
zeros = tf.zeros(squarish_squares.shape)
zeros

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [43]:
# tf.Tensor 형태 변경(numpy와 동일하게 reshape,pytorch는 view)
rank_three_tensor = tf.ones([3,4,5])
print(rank_three_tensor.shape)
matrix = tf.reshape(rank_three_tensor,[6,10])   # 기존 행렬을 6x10 행렬로 변경

print(matrix.shape)
matrixB = tf.reshape(matrix, [3,-1])

print(matrixB.shape)

(3, 4, 5)
(6, 10)
(3, 20)


In [44]:
#정수형 텐서 실수형으로 변환
a=tf.constant([1,2,3])
print(a)

float_tensor = tf.cast(tf.constant([1,2,3]),dtype=tf.float32)
float_tensor

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>